Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/11/2022
Var
peso:real
altura:real
resposta:real

Inicio
escreval("Digite seu peso:")
leia(peso)
escreval("Digite sua altura:")
leia(altura)
resposta<-peso/altura*altura
escreval("seu IMC é de:",resposta)




Fimalgoritmo